/* ECO Opening code lookup — A00-E99 */
var ECO_MAP = {
  'A00': 'Polish Opening',
  'A01': 'Nimzovich-Larsen Attack',
  'A02': 'Bird\'s Opening',
  'A03': 'Bird\'s Opening',
  'A04': 'Reti Opening',
  'A05': 'Reti Opening',
  'A06': 'Reti Opening',
  'A07': 'Reti Opening',
  'A08': 'Reti Opening',
  'A09': 'Reti Opening',
  'A10': 'English Opening',
  'A11': 'English Opening',
  'A12': 'English Opening',
  'A13': 'English Opening',
  'A14': 'English Opening',
  'A15': 'English Opening',
  'A16': 'English Opening',
  'A17': 'English Opening',
  'A18': 'English Opening',
  'A19': 'English Opening',
  'A20': 'English Opening',
  'A21': 'English Opening',
  'A22': 'English Opening',
  'A23': 'English Opening',
  'A24': 'English Opening',
  'A25': 'English Opening',
  'A26': 'English Opening',
  'A27': 'English Opening',
  'A28': 'English Opening',
  'A29': 'English Opening',
  'A30': 'English Opening',
  'A31': 'English Opening',
  'A32': 'English Opening',
  'A33': 'English Opening',
  'A34': 'English Opening',
  'A35': 'English Opening',
  'A36': 'English Opening',
  'A37': 'English Opening',
  'A38': 'English Opening',
  'A39': 'English Opening',
  'A40': 'Queen\'s Pawn',
  'A41': 'Queen\'s Pawn',
  'A42': 'Modern Defence, Averbakh System',
  'A43': 'Old Benoni Defence',
  'A44': 'Old Benoni Defence',
  'A45': 'Queen\'s Pawn Game',
  'A46': 'Queen\'s Pawn Game',
  'A47': 'Queen\'s Indian Defence',
  'A48': 'King\'s Indian, East Indian Defence',
  'A49': 'King\'s Indian, East Indian Defence',
  'A50': 'Queen\'s Pawn Game',
  'A51': 'Budapest Defence',
  'A52': 'Budapest Defence',
  'A53': 'Old Indian Defence',
  'A54': 'Old Indian Defence',
  'A55': 'Old Indian Defence',
  'A56': 'Benoni Defence',
  'A57': 'Benko Gambit',
  'A58': 'Benko Gambit',
  'A59': 'Benko Gambit',
  'A60': 'Benoni Defence',
  'A61': 'Benoni Defence',
  'A62': 'Benoni Defence',
  'A63': 'Benoni Defence',
  'A64': 'Benoni Defence',
  'A65': 'Benoni Defence',
  'A66': 'Benoni Defence',
  'A67': 'Benoni Defence',
  'A68': 'Benoni Defence',
  'A69': 'Benoni Defence',
  'A70': 'Benoni Defence',
  'A71': 'Benoni Defence',
  'A72': 'Benoni Defence',
  'A73': 'Benoni Defence',
  'A74': 'Benoni Defence',
  'A75': 'Benoni Defence',
  'A76': 'Benoni Defence',
  'A77': 'Benoni Defence',
  'A78': 'Benoni Defence',
  'A79': 'Benoni Defence',
  'A80': 'Dutch Opening',
  'A81': 'Dutch Opening',
  'A82': 'Dutch Opening',
  'A83': 'Dutch Opening',
  'A84': 'Dutch Opening',
  'A85': 'Dutch Opening',
  'A86': 'Dutch Opening',
  'A87': 'Dutch Opening',
  'A88': 'Dutch Opening',
  'A89': 'Dutch Opening',
  'A90': 'Dutch Opening',
  'A91': 'Dutch Opening',
  'A92': 'Dutch Opening',
  'A93': 'Dutch Opening',
  'A94': 'Dutch Opening',
  'A95': 'Dutch Opening',
  'A96': 'Dutch Opening',
  'A97': 'Dutch Opening',
  'A98': 'Dutch Opening',
  'A99': 'Dutch Opening',
  'B00': 'King\'s Pawn Opening',
  'B01': 'Scandinavian Defence',
  'B02': 'Alekhine\'s Defence',
  'B03': 'Alekhine\'s Defence',
  'B04': 'Alekhine\'s Defence',
  'B05': 'Alekhine\'s Defence',
  'B06': 'Modern Defence',
  'B07': 'Pirc Defence',
  'B08': 'Pirc Defence',
  'B09': 'Pirc Defence',
  'B10': 'Caro-Kann Defence',
  'B11': 'Caro-Kann Defence',
  'B12': 'Caro-Kann Defence',
  'B13': 'Caro-Kann Defence',
  'B14': 'Caro-Kann Defence',
  'B15': 'Caro-Kann Defence',
  'B16': 'Caro-Kann Defence',
  'B17': 'Caro-Kann Defence',
  'B18': 'Caro-Kann Defence',
  'B19': 'Caro-Kann Defence',
  'B20': 'Sicilian Defence',
  'B21': 'Sicilian Defence',
  'B22': 'Sicilian Defence',
  'B23': 'Sicilian Defence',
  'B24': 'Sicilian Defence',
  'B25': 'Sicilian Defence',
  'B26': 'Sicilian Defence',
  'B27': 'Sicilian Defence',
  'B28': 'Sicilian Defence',
  'B29': 'Sicilian Defence',
  'B30': 'Sicilian Defence',
  'B31': 'Sicilian Defence',
  'B32': 'Sicilian Defence',
  'B33': 'Sicilian Defence',
  'B34': 'Sicilian Defence',
  'B35': 'Sicilian Defence',
  'B36': 'Sicilian Defence',
  'B37': 'Sicilian Defence',
  'B38': 'Sicilian Defence',
  'B39': 'Sicilian Defence',
  'B40': 'Sicilian Defence',
  'B41': 'Sicilian Defence',
  'B42': 'Sicilian Defence',
  'B43': 'Sicilian Defence',
  'B44': 'Sicilian Defence',
  'B45': 'Sicilian Defence',
  'B46': 'Sicilian Defence',
  'B47': 'Sicilian Defence',
  'B48': 'Sicilian Defence',
  'B49': 'Sicilian Defence',
  'B50': 'Sicilian Defence',
  'B51': 'Sicilian Defence',
  'B52': 'Sicilian Defence',
  'B53': 'Sicilian Defence',
  'B54': 'Sicilian Defence',
  'B55': 'Sicilian Defence',
  'B56': 'Sicilian Defence',
  'B57': 'Sicilian Defence',
  'B58': 'Sicilian Defence',
  'B59': 'Sicilian Defence',
  'B60': 'Sicilian Defence',
  'B61': 'Sicilian Defence',
  'B62': 'Sicilian Defence',
  'B63': 'Sicilian Defence',
  'B64': 'Sicilian Defence',
  'B65': 'Sicilian Defence',
  'B66': 'Sicilian Defence',
  'B67': 'Sicilian Defence',
  'B68': 'Sicilian Defence',
  'B69': 'Sicilian Defence',
  'B70': 'Sicilian Defence',
  'B71': 'Sicilian Defence',
  'B72': 'Sicilian Defence',
  'B73': 'Sicilian Defence',
  'B74': 'Sicilian Defence',
  'B75': 'Sicilian Defence',
  'B76': 'Sicilian Defence',
  'B77': 'Sicilian Defence',
  'B78': 'Sicilian Defence',
  'B79': 'Sicilian Defence',
  'B80': 'Sicilian Defence',
  'B81': 'Sicilian Defence',
  'B82': 'Sicilian Defence',
  'B83': 'Sicilian Defence',
  'B84': 'Sicilian Defence',
  'B85': 'Sicilian Defence',
  'B86': 'Sicilian Defence',
  'B87': 'Sicilian Defence',
  'B88': 'Sicilian Defence',
  'B89': 'Sicilian Defence',
  'B90': 'Sicilian Defence',
  'B91': 'Sicilian Defence',
  'B92': 'Sicilian Defence',
  'B93': 'Sicilian Defence',
  'B94': 'Sicilian Defence',
  'B95': 'Sicilian Defence',
  'B96': 'Sicilian Defence',
  'B97': 'Sicilian Defence',
  'B98': 'Sicilian Defence',
  'B99': 'Sicilian Defence',
  'C00': 'French Defence',
  'C01': 'French Defence',
  'C02': 'French Defence',
  'C03': 'French Defence',
  'C04': 'French Defence',
  'C05': 'French Defence',
  'C06': 'French Defence',
  'C07': 'French Defence',
  'C08': 'French Defence',
  'C09': 'French Defence',
  'C10': 'French Defence',
  'C11': 'French Defence',
  'C12': 'French Defence',
  'C13': 'French Defence',
  'C14': 'French Defence',
  'C15': 'French Defence',
  'C16': 'French Defence',
  'C17': 'French Defence',
  'C18': 'French Defence',
  'C19': 'French Defence',
  'C20': 'King\'s Pawn Game',
  'C21': 'Centre Game',
  'C22': 'Centre Game',
  'C23': 'Bishop\'s Opening',
  'C24': 'Bishop\'s Opening',
  'C25': 'Vienna Game',
  'C26': 'Vienna Game',
  'C27': 'Vienna Game',
  'C28': 'Vienna Game',
  'C29': 'Vienna Game',
  'C30': 'King\'s Gambit',
  'C31': 'King\'s Gambit',
  'C32': 'King\'s Gambit',
  'C33': 'King\'s Gambit',
  'C34': 'King\'s Gambit',
  'C35': 'King\'s Gambit',
  'C36': 'King\'s Gambit',
  'C37': 'King\'s Gambit',
  'C38': 'King\'s Gambit',
  'C39': 'King\'s Gambit',
  'C40': 'King\'s Knight Opening',
  'C41': 'Philidor\'s Defence',
  'C42': 'Petrov\'s Defence',
  'C43': 'Petrov\'s Defence',
  'C44': 'King\'s Pawn Game',
  'C45': 'Scotch Game',
  'C46': 'Three Knights Game',
  'C47': 'Four Knights, Scotch Variation',
  'C48': 'Four Knights, Scotch Variation',
  'C49': 'Four Knights, Scotch Variation',
  'C50': 'Italian Game',
  'C51': 'Evans Gambit',
  'C52': 'Evans Gambit',
  'C53': 'Giuoco Piano',
  'C54': 'Giuoco Piano',
  'C55': 'Two Knights Defence',
  'C56': 'Two Knights Defence',
  'C57': 'Two Knights Defence',
  'C58': 'Two Knights Defence',
  'C59': 'Two Knights Defence',
  'C60': 'Ruy Lopez Opening',
  'C61': 'Ruy Lopez Opening',
  'C62': 'Ruy Lopez Opening',
  'C63': 'Ruy Lopez Opening',
  'C64': 'Ruy Lopez Opening',
  'C65': 'Ruy Lopez Opening',
  'C66': 'Ruy Lopez Opening',
  'C67': 'Ruy Lopez Opening',
  'C68': 'Ruy Lopez Opening',
  'C69': 'Ruy Lopez Opening',
  'C70': 'Ruy Lopez Opening',
  'C71': 'Ruy Lopez Opening',
  'C72': 'Ruy Lopez Opening',
  'C73': 'Ruy Lopez Opening',
  'C74': 'Ruy Lopez Opening',
  'C75': 'Ruy Lopez Opening',
  'C76': 'Ruy Lopez Opening',
  'C77': 'Ruy Lopez Opening',
  'C78': 'Ruy Lopez Opening',
  'C79': 'Ruy Lopez Opening',
  'C80': 'Ruy Lopez Opening',
  'C81': 'Ruy Lopez Opening',
  'C82': 'Ruy Lopez Opening',
  'C83': 'Ruy Lopez Opening',
  'C84': 'Ruy Lopez Opening',
  'C85': 'Ruy Lopez Opening',
  'C86': 'Ruy Lopez Opening',
  'C87': 'Ruy Lopez Opening',
  'C88': 'Ruy Lopez Opening',
  'C89': 'Ruy Lopez Opening',
  'C90': 'Ruy Lopez Opening',
  'C91': 'Ruy Lopez Opening',
  'C92': 'Ruy Lopez Opening',
  'C93': 'Ruy Lopez Opening',
  'C94': 'Ruy Lopez Opening',
  'C95': 'Ruy Lopez Opening',
  'C96': 'Ruy Lopez Opening',
  'C97': 'Ruy Lopez Opening',
  'C98': 'Ruy Lopez Opening',
  'C99': 'Ruy Lopez Opening',
  'D00': 'Queen\'s Pawn Game',
  'D01': 'Richter-Veresov Attack',
  'D02': 'Queen\'s Pawn Game',
  'D03': 'Torre Attack',
  'D04': 'Queen\'s Pawn Game',
  'D05': 'Queen\'s Pawn Game',
  'D06': 'Queen\'s Gambit',
  'D07': 'Queen\'s Gambit, Chigorin Defence',
  'D08': 'Queen\'s Gambit, Chigorin Defence',
  'D09': 'Queen\'s Gambit, Chigorin Defence',
  'D10': 'Queen\'s Gambit, Slav Defence',
  'D11': 'Queen\'s Gambit, Slav Defence',
  'D12': 'Queen\'s Gambit, Slav Defence',
  'D13': 'Queen\'s Gambit, Slav Defence',
  'D14': 'Queen\'s Gambit, Slav Defence',
  'D15': 'Queen\'s Gambit, Slav Defence',
  'D16': 'Queen\'s Gambit, Slav accepted',
  'D17': 'Queen\'s Gambit, Slav, Czech Defence',
  'D18': 'Queen\'s Gambit, Slav, Czech Defence',
  'D19': 'Queen\'s Gambit, Slav, Czech Defence',
  'D20': 'Queen\'s Gambit Accepted',
  'D21': 'Queen\'s Gambit Accepted',
  'D22': 'Queen\'s Gambit Accepted',
  'D23': 'Queen\'s Gambit Accepted',
  'D24': 'Queen\'s Gambit Accepted',
  'D25': 'Queen\'s Gambit Accepted',
  'D26': 'Queen\'s Gambit Accepted',
  'D27': 'Queen\'s Gambit Accepted',
  'D28': 'Queen\'s Gambit Accepted',
  'D29': 'Queen\'s Gambit Accepted',
  'D30': 'Queen\'s Gambit Declined',
  'D31': 'Queen\'s Gambit Declined',
  'D32': 'Queen\'s Gambit Declined',
  'D33': 'Queen\'s Gambit Declined',
  'D34': 'Queen\'s Gambit Declined',
  'D35': 'Queen\'s Gambit Declined',
  'D36': 'Queen\'s Gambit Declined',
  'D37': 'Queen\'s Gambit Declined',
  'D38': 'Queen\'s Gambit Declined',
  'D39': 'Queen\'s Gambit Declined',
  'D40': 'Queen\'s Gambit Declined',
  'D41': 'Queen\'s Gambit Declined',
  'D42': 'Queen\'s Gambit Declined',
  'D43': 'Queen\'s Gambit Declined, Semi-Slav',
  'D44': 'Queen\'s Gambit Declined, Semi-Slav',
  'D45': 'Queen\'s Gambit Declined, Semi-Slav',
  'D46': 'Queen\'s Gambit Declined, Semi-Slav',
  'D47': 'Queen\'s Gambit Declined, Semi-Slav',
  'D48': 'Queen\'s Gambit Declined, Semi-Slav',
  'D49': 'Queen\'s Gambit Declined, Semi-Slav',
  'D50': 'Queen\'s Gambit Declined',
  'D51': 'Queen\'s Gambit Declined',
  'D52': 'Queen\'s Gambit Declined',
  'D53': 'Queen\'s Gambit Declined',
  'D54': 'Queen\'s Gambit Declined',
  'D55': 'Queen\'s Gambit Declined',
  'D56': 'Queen\'s Gambit Declined',
  'D57': 'Queen\'s Gambit Declined',
  'D58': 'Queen\'s Gambit Declined',
  'D59': 'Queen\'s Gambit Declined',
  'D60': 'Queen\'s Gambit Declined',
  'D61': 'Queen\'s Gambit Declined',
  'D62': 'Queen\'s Gambit Declined',
  'D63': 'Queen\'s Gambit Declined',
  'D64': 'Queen\'s Gambit Declined',
  'D65': 'Queen\'s Gambit Declined',
  'D66': 'Queen\'s Gambit Declined',
  'D67': 'Queen\'s Gambit Declined',
  'D68': 'Queen\'s Gambit Declined',
  'D69': 'Queen\'s Gambit Declined',
  'D70': 'Neo-Gruenfeld Defence',
  'D71': 'Neo-Gruenfeld Defence',
  'D72': 'Neo-Gruenfeld Defence',
  'D73': 'Neo-Gruenfeld Defence',
  'D74': 'Neo-Gruenfeld Defence',
  'D75': 'Neo-Gruenfeld Defence',
  'D76': 'Neo-Gruenfeld Defence',
  'D77': 'Neo-Gruenfeld Defence',
  'D78': 'Neo-Gruenfeld Defence',
  'D79': 'Neo-Gruenfeld Defence',
  'D80': 'Gruenfeld Defence',
  'D81': 'Gruenfeld Defence',
  'D82': 'Gruenfeld Defence',
  'D83': 'Gruenfeld Defence',
  'D84': 'Gruenfeld Defence',
  'D85': 'Gruenfeld Defence',
  'D86': 'Gruenfeld Defence',
  'D87': 'Gruenfeld Defence',
  'D88': 'Gruenfeld Defence',
  'D89': 'Gruenfeld Defence',
  'D90': 'Gruenfeld Defence',
  'D91': 'Gruenfeld Defence',
  'D92': 'Gruenfeld Defence',
  'D93': 'Gruenfeld Defence',
  'D94': 'Gruenfeld Defence',
  'D95': 'Gruenfeld Defence',
  'D96': 'Gruenfeld Defence',
  'D97': 'Gruenfeld Defence',
  'D98': 'Gruenfeld Defence',
  'D99': 'Gruenfeld Defence',
  'E00': 'Queen\'s Pawn Game',
  'E01': 'Catalan, Closed',
  'E02': 'Catalan, Closed',
  'E03': 'Catalan, Closed',
  'E04': 'Catalan, Closed',
  'E05': 'Catalan, Closed',
  'E06': 'Catalan, Closed',
  'E07': 'Catalan, Closed',
  'E08': 'Catalan, Closed',
  'E09': 'Catalan, Closed',
  'E10': 'Queen\'s Pawn Game',
  'E11': 'Bogo-Indian Defence',
  'E12': 'Queen\'s Indian Defence',
  'E13': 'Queen\'s Indian Defence',
  'E14': 'Queen\'s Indian Defence',
  'E15': 'Queen\'s Indian Defence',
  'E16': 'Queen\'s Indian Defence',
  'E17': 'Queen\'s Indian Defence',
  'E18': 'Queen\'s Indian Defence',
  'E19': 'Queen\'s Indian Defence',
  'E20': 'Nimzo-Indian Defence',
  'E21': 'Nimzo-Indian Defence',
  'E22': 'Nimzo-Indian Defence',
  'E23': 'Nimzo-Indian Defence',
  'E24': 'Nimzo-Indian Defence',
  'E25': 'Nimzo-Indian Defence',
  'E26': 'Nimzo-Indian Defence',
  'E27': 'Nimzo-Indian Defence',
  'E28': 'Nimzo-Indian Defence',
  'E29': 'Nimzo-Indian Defence',
  'E30': 'Nimzo-Indian Defence',
  'E31': 'Nimzo-Indian Defence',
  'E32': 'Nimzo-Indian Defence',
  'E33': 'Nimzo-Indian Defence',
  'E34': 'Nimzo-Indian Defence',
  'E35': 'Nimzo-Indian Defence',
  'E36': 'Nimzo-Indian Defence',
  'E37': 'Nimzo-Indian Defence',
  'E38': 'Nimzo-Indian Defence',
  'E39': 'Nimzo-Indian Defence',
  'E40': 'Nimzo-Indian Defence',
  'E41': 'Nimzo-Indian Defence',
  'E42': 'Nimzo-Indian Defence',
  'E43': 'Nimzo-Indian Defence',
  'E44': 'Nimzo-Indian Defence',
  'E45': 'Nimzo-Indian Defence',
  'E46': 'Nimzo-Indian Defence',
  'E47': 'Nimzo-Indian Defence',
  'E48': 'Nimzo-Indian Defence',
  'E49': 'Nimzo-Indian Defence',
  'E50': 'Nimzo-Indian Defence',
  'E51': 'Nimzo-Indian Defence',
  'E52': 'Nimzo-Indian Defence',
  'E53': 'Nimzo-Indian Defence',
  'E54': 'Nimzo-Indian Defence',
  'E55': 'Nimzo-Indian Defence',
  'E56': 'Nimzo-Indian Defence',
  'E57': 'Nimzo-Indian Defence',
  'E58': 'Nimzo-Indian Defence',
  'E59': 'Nimzo-Indian Defence',
  'E60': 'King\'s Indian Defence',
  'E61': 'King\'s Indian Defence',
  'E62': 'King\'s Indian Defence',
  'E63': 'King\'s Indian Defence',
  'E64': 'King\'s Indian Defence',
  'E65': 'King\'s Indian Defence',
  'E66': 'King\'s Indian Defence',
  'E67': 'King\'s Indian Defence',
  'E68': 'King\'s Indian Defence',
  'E69': 'King\'s Indian Defence',
  'E70': 'King\'s Indian Defence',
  'E71': 'King\'s Indian Defence',
  'E72': 'King\'s Indian Defence',
  'E73': 'King\'s Indian Defence',
  'E74': 'King\'s Indian Defence',
  'E75': 'King\'s Indian Defence',
  'E76': 'King\'s Indian Defence',
  'E77': 'King\'s Indian Defence',
  'E78': 'King\'s Indian Defence',
  'E79': 'King\'s Indian Defence',
  'E80': 'King\'s Indian Defence',
  'E81': 'King\'s Indian Defence',
  'E82': 'King\'s Indian Defence',
  'E83': 'King\'s Indian Defence',
  'E84': 'King\'s Indian Defence',
  'E85': 'King\'s Indian Defence',
  'E86': 'King\'s Indian Defence',
  'E87': 'King\'s Indian Defence',
  'E88': 'King\'s Indian Defence',
  'E89': 'King\'s Indian Defence',
  'E90': 'King\'s Indian Defence',
  'E91': 'King\'s Indian Defence',
  'E92': 'King\'s Indian Defence',
  'E93': 'King\'s Indian Defence',
  'E94': 'King\'s Indian Defence',
  'E95': 'King\'s Indian Defence',
  'E96': 'King\'s Indian Defence',
  'E97': 'King\'s Indian Defence',
  'E98': 'King\'s Indian Defence',
  'E99': 'King\'s Indian Defence'
};